name: Build App

on:
    push:
        branches:
        - master

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: build-push
          uses: docker/build-push-action@v1
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
            registry: docker.io
            repository: sweli0/cd
            tag_with_sha: true
        ‐ name: push
          uses: docker/push-action@v1
          with:
            registry: myregistry
            tags: ${{ outputs.build.tags }}